<program> ::= <statement>
<statement> ::= <expression>
<expression> ::= <term> | <expression> <binary_op> <term>
<term> ::= <factor> | <term> <binary_op> <factor>
<factor> ::= NUMBER | LPAREN <expression> RPAREN | <unary_op> <factor>
<binary_op> ::= PLUS | MINUS | MULTIPLY | DIVIDE
<unary_op> ::= PLUS | MINUS